# This file was generated by GoReleaser. DO NOT EDIT.
cask "contract-cli" do
  version "1.22.2"

  on_macos do
    on_intel do
      sha256 "6b866ddc0c543b5868b5adeda6486cd763653f59c70671a6ed26172dfecafda0"
      url "https://github.com/ibm-hyper-protect/contract-cli/releases/download/v#{version}/contract-cli_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/ibm-hyper-protect/contract-cli"
    end
    on_arm do
      sha256 "392251a32003e1e92b5647b2829bdd24a3950599cb7b80ce14cf167b5551d478"
      url "https://github.com/ibm-hyper-protect/contract-cli/releases/download/v#{version}/contract-cli_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/ibm-hyper-protect/contract-cli"
    end
  end

  on_linux do
    on_intel do
      sha256 "98ce959d3ffce0a70fd8844ceb0be1c6efdef8a2ff03099922cdcbdd4cdc4a97"
      url "https://github.com/ibm-hyper-protect/contract-cli/releases/download/v#{version}/contract-cli_#{version}_linux_amd64.tar.gz",
        verified: "github.com/ibm-hyper-protect/contract-cli"
    end
    on_arm do
      sha256 "a5b30b801fcebf95c956a7f575e98e9a02eff11ff385f35f5cb295daa828a2b3"
      url "https://github.com/ibm-hyper-protect/contract-cli/releases/download/v#{version}/contract-cli_#{version}_linux_arm64.tar.gz",
        verified: "github.com/ibm-hyper-protect/contract-cli"
    end
  end

  name "contract-cli"
  desc "CLI tool for managing IBM Confidential Computing contracts and configurations"
  homepage "https://github.com/ibm-hyper-protect/contract-cli"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "openssl",
    ]

  binary "contract-cli"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/contract-cli"]
    end
  end

  # No zap stanza required

end
